kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-pv-volume
  labels:
    usage: mongo-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: mongo-secret
    shareName: mongodb
    readOnly: false