apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: "mongo-snacks"
    release: "MongoDB-v4.0.8"
spec:
  template:
    metadata:
      labels:
        app: "mongo-snacks"
        release: "MongoDB-v4.0.8"
    spec:
      containers:
      - name: mongo-snacks
        image: mongo:4.0.8
        imagePullPolicy: Always
        env:
        - name: MONGODB_DATABASE
          value: jx-workshop 
        ports:
        - name: mongodb
          containerPort: 27017
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        volumeMounts:
        - name: db-data
          mountPath: /data/db
        resources:
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: mongo-pv-claim
