apiVersion: v1
kind: Service
metadata:
  name: "mongo"
  labels:
    app: "mongo-snacks"
    release: "MongoDB-v4.0.8"
spec:
  type: NodePort
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  selector:
    app: "mongo-snacks"

