apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: snacks-service
  labels:
    app: "snacks-service"
    release: "snacks-latest"
spec:
  template:
    metadata:
      labels:
        app: "snacks-service"
        release: "snacks-latest"
    spec:
      containers:
      - name: snacks
        image: local/snacks:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker-stack
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
